= Class Dependency Scanner

image:https://travis-ci.org/janbeernink/class-dependency-scanner.svg?branch=develop["Build Status", link="https://travis-ci.org/janbeernink/class-dependency-scanner"]

This is a small experimental Java library to analyze the dependencies between classes and generate a dependency graph.

== Usage

The following example shows how to generate a dependency graph for class String:
[source,java,indent=0]
----
DependencyGraphNode startingNode = new ClassDependencyScanner().buildDependencyGraph(String.class);
----

This will return a DependencyGraphNode that represents the String class. This node can be used as a starting point to iterate over the entire graph:

[source,java,indent=0]
----
for (DependencyGraphNode node: startingNode) {
        // Do something useful
}
----

The iterator returned by the iterator() method on DependencyGraphNode is guaranteed to visit each node exactly once, even when there are cycles in the graph.

== Known issues

* Annotations are not yet fully processed.

== License

This project is licensed under the Apache Software License, Version 2.0, please see the LICENSE file for more details.
